version: "3.7"

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7.35
    restart: always
    environment:
      - ./backend/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data: